semantic_score:
  train_score_cache_path: results/cache/swe_care_context_slices_semantic_train_exact.json.gz
  dev_score_cache_path: results/cache/swe_care_context_slices_semantic_dev_exact.json.gz
  test_score_cache_path: results/cache/swe_care_context_slices_semantic_test_exact.json.gz

semantic_char_score:
  train_score_cache_path: results/cache/swe_care_context_slices_semantic_char_train_exact.json.gz
  dev_score_cache_path: results/cache/swe_care_context_slices_semantic_char_dev_exact.json.gz
  test_score_cache_path: results/cache/swe_care_context_slices_semantic_char_test_exact.json.gz

semantic_file_score:
  train_score_cache_path: results/cache/swe_care_context_slices_semantic_file_mean_train_exact.json.gz
  dev_score_cache_path: results/cache/swe_care_context_slices_semantic_file_mean_dev_exact.json.gz
  test_score_cache_path: results/cache/swe_care_context_slices_semantic_file_mean_test_exact.json.gz

semantic_char_file_score:
  train_score_cache_path: results/cache/swe_care_context_slices_semantic_char_file_mean_train_exact.json.gz
  dev_score_cache_path: results/cache/swe_care_context_slices_semantic_char_file_mean_dev_exact.json.gz
  test_score_cache_path: results/cache/swe_care_context_slices_semantic_char_file_mean_test_exact.json.gz

semantic_procedural_char_score:
  train_score_cache_path: results/cache/swe_care_context_slices_semantic_char_file_mean_procedural_char_train_exact.json.gz
  dev_score_cache_path: results/cache/swe_care_context_slices_semantic_char_file_mean_procedural_char_dev_exact.json.gz
  test_score_cache_path: results/cache/swe_care_context_slices_semantic_char_file_mean_procedural_char_test_exact.json.gz
